### PR TITLE
refactor: highlight creation and validation

### PR DESCRIPTION
**Pull request by willothy**
Continuing from #19 - honestly this might make more sense as an external library to be copy/pasted around by various plugins and I'll likely reuse it for mine.

### CODE REVIEW

**Review by nyngwang — APPROVED** [review]
@willothy Thank you! Let me know if this can be merged!

**Comment by willothy** [comment]
Wait don't merge! Just noticed a bug

**Comment by nyngwang** [comment]
Take your time~ I'm also busy recently. What I can do is just trust every line of your code since I have no time to double-check. Just tag me if it's safe to merge (and it's OK to have some follow-up PR for improving it iteratively)

**Comment by willothy** [comment]
@nyngwang alright, should be safe to merge!

**Review by nyngwang — APPROVED** [review]
Thank you!

**Comment by nyngwang** [comment]
@willothy I'm not sure ,but it seems that it causes some downgrade of performance.

**Comment by willothy** [comment]
> @willothy I'm not sure ,but it seems that it causes some downgrade of performance.

In terms of startup time? Maybe slightly, though it shouldn't be too much. I can remove some of the checks and see if it gets better. What sort of issues are you seeing? I'm still seeing startup in the 1ms range.

**Comment by nyngwang** [comment]
@willothy My last comment above might be wrong. I was running nvim-dap on my remote server to debug a kinda complex pytorch project. The experience might be caused by other reasons. Apologies if this might make you worry.

Just to confirm: the code in this PR will only be run once, right?

**Comment by willothy** [comment]
> @willothy My last comment above might be wrong. I was running nvim-dap on my remote server to debug a kinda complex pytorch project. The experience might be caused by other reasons. Apologies if this might make you worry.
> 
> Just to confirm: the code in this PR will only be run once, right?

Yes, it should only run on setup(). No worries! I'll look into it if there are any issues, wouldn't want to slow the plugin down :)

**Pull request merged**
